global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'health-api'
    static_configs:
      - targets: ['localhost:3000']

  - job_name: 'user-service'
    static_configs:
      - targets: ['localhost:4001']

  - job_name: 'health-data-service'
    static_configs:
      - targets: ['localhost:4002']

  - job_name: 'ai-service'
    static_configs:
      - targets: ['localhost:4003']

alerting:
  alertmanagers:
    - static_configs:
      - targets: ['localhost:9093']

rule_files:
  - 'alert.rules.yml' 